name: Build And Publish Nuget

on: 
  release:
    types: [created]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: |  
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\src\LiquidTechnologies.FastInfoSet -t:restore
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\src\LiquidTechnologies.FastInfoSet /property:Configuration=Release
    - name: Publish Nuget to registry
      run: dotnet nuget push .\src\LiquidTechnologies.FastInfoSet\bin\Release\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://www.nuget.org/api/v2/package
